pipeline {
    agent{
        node {
            label 'Slave'
        }
    }
    
    environment {
        GITHUB_CREDENTIALS = credentials('2474e17d-8585-4519-b614-0aaaf0f0ed18')
        //REMOTE_EC2_IP = '54.205.183.102'
        EC2_SSH_CREDENTIALS = '9bd2408c-e040-4f9e-a11b-133a47f4906f'
        //WORKING_DIRECTORY = '/var/www/html/'
    }
    
    stages {
        stage('Check Host') {
            steps {
                sh "hostname"
            }
        }
        stage('Verify IP') {
            steps {
                sh "curl ifconfig.me"
            }
        }
        stage('Check Directory') {
            steps {
                sh "pwd"
            }
        }
        stage('Set Permissions'){
            steps{
                sh "sudo chmod +x ./Lab/task.sh"
            }
        }
        stage('Execute Task') {
            steps {
                sh "./Lab/task.sh"
            }
        }
        stage('Build') {
            steps {
                sh "sudo docker build -t app:latest ./Lab/"
            }
        }
        stage('Deploy') {
            steps {
                sh "sudo docker run -d -p 5000:5000 app:latest"
            }
        }
        stage('Archive Artifacts') {
            steps {
                sh "echo 'Archiving Artifacts'"
                //archiveArtifacts 'target/*.jar'
            }
        }

    }
}