pipeline {
    agent{
        node {
            label 'Slave'
        }
    }
    /*
    environment {
        GITHUB_CREDENTIALS = credentials('4bce3c62-c683-41d9-bc63-d9ffd4385df7')
        REMOTE_EC2_IP = '54.205.183.102'
        EC2_SSH_CREDENTIALS = 'd608d6af-e1f6-41ea-9d46-e6502262e197'
        WORKING_DIRECTORY = '/var/www/html/'
    }
    */
    stages {
        stage('Check Host') {
            steps {
                sh "hostname"
            }
        }
        stage('Verify IP') {
            steps {
                sh "curl ifconfig.me"
            }
        }
        stage('Check Directory') {
            steps {
                sh "pwd"
            }
        }
        /*
        stage('Build'){
            steps{
                sh "git pull origin main"
            }
        }
        stage('Archive Artifacts') {
            steps {
                archiveArtifacts 'target/*.jar'
            }
        }
        */
    }
}